// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CustomersController from "./customers_controller"
application.register("customers", CustomersController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InvoiceProductsController from "./invoice_products_controller"
application.register("invoice-products", InvoiceProductsController)

import InvoicesController from "./invoices_controller"
application.register("invoices", InvoicesController)
